feat(services): add quote-management/getAQuote endpoint
bikboktech/musicology-api.pro pull request #11
Opened 2023-08-15 10:23 UTC by andhrelja

2023-08-15 11:54 UTC, andhrelja commented
Implement form validation using [yup](https://github.com/jquense/yup) instead of manually

2023-08-15 12:04 UTC, andhrelja commented
Create a `quotes` table to store `get-a-quote` results. 

Question for Manuel on user activation (whether-or):
1. Once a `quote` record is approved by an Admin, the "krnji" user becomes an "active" user
2. Once an  `account` record is approved by an Admin, the "krnji" user becomes an "active" user

2023-09-21 17:36 UTC, bikboktech requested changes

2023-09-21 17:36 UTC, bikboktech commented on app.js
> +import authRoutes from "./source/auth/routes.js";
sort

2023-09-21 17:36 UTC, bikboktech commented on app.js
> +// app.use(spotifyAuth);
uncomment

2023-09-21 17:36 UTC, bikboktech commented on package.json
> +    "joi": "^17.10.2",
use yup dammit

2023-09-21 17:36 UTC, bikboktech commented on source/common/data/knexfile.js
> +dotenv.config();
try without dotenv

2023-09-21 17:36 UTC, bikboktech commented on source/common/data/migrations/003_create_alter_entity_deps.cjs
> +    knex.schema.alterTable('posts', table => {
await

2023-09-21 17:36 UTC, bikboktech commented on source/common/data/migrations/003_create_alter_entity_deps.cjs
> +    knex.schema.alterTable('posts', table => {
await

2023-09-21 17:36 UTC, bikboktech commented on source/common/data/migrations/003_create_alter_entity_deps.cjs
> +    knex.schema.alterTable('events', table => {
await

2023-09-21 17:36 UTC, bikboktech commented on source/common/data/migrations/003_create_alter_entity_deps.cjs
> +    knex.schema.alterTable('accounts', table => {
await

2023-09-21 20:59 UTC, bikboktech commented on source/common/data/knexfile.js
> +dotenv.config();
works without dotenv

2023-09-23 09:21 UTC, bikboktech approved these changes

2023-09-23 09:21 UTC, merged